
spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://45.119.146.45:3306/Itsreceipt?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: footcoder
    password: vntzhejWkd321!
    driverClassName: com.mysql.jdbc.Driver
    tomcat:
      initial-size: 1
      min-idle: 1
      max-idle: 2
      max-active: 2
      max-wait: 10000
    hikari:
      maximum-pool-size: 5
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      pool-name: receipt-hikari
  redis:
    host: 45.119.146.45
    port: 6379
    ssl: false
    timeout: 10s
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: 5s



logging:
  level:
    org.springframework.web: DEBUG
    kr.footcoder.receipt: DEBUG