# java -jar -Dspring.profiles.active={development|production}
# application-development.yml | application-production.yml
spring:
  profiles:
    active: development
#    active: production

mybatis:
  type-aliases-package: kr.footcoder.receipt.domain;
  mapper-locations: classpath:mappers/*.xml
  configuration:
    default-statement-timeout: 120