# java -jar -Dspring.profiles.active={development|production}
# application-development.yml | application-production.yml
spring:
  profiles:
    active: development
  session:
    store-type: redis
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
    port: 8080
    servlet:
      session:
        timeout: 30m


mybatis:
  type-aliases-package: kr.footcoder.receipt.domain;
  mapper-locations: classpath:mappers/*.xml
  configuration:
    default-statement-timeout: 120